### ISSUE TITLE
Contacting the dev

### ISSUE THREAD

**Issue by ujicos** [ClementDreptin/Hayzen#1]
Hey, is there any way i could contact you? I am attempting to create my own xex for a different cod game, but lacking the knowledge of how to start. Ive done multiple C++ dll for cod on pc so i know iud be able to

**Comment by ClementDreptin** [comment]
Hi,

I have a repository that contains a step-by-step tutorial on how to make a DashLaunch plugin (XEX), as well as some additional info about creating mods in general.
The repository is [here](https://github.com/ClementDreptin/ModdingResources), it will guide you from setting up the console and your development environment to writing a simple plugin that displays a HUD element on MW2. If you have some C++ experience and have disassembled game before, you should be able to skip a few sections but I still recommend reading everything (it's not that long).

I hope it helps.

Cheers

**Comment by ujicos** [comment]
Thank you for such a quick reply. I can see a lot of what i need is in there.
How would i go about finding stuff like gentity?
For reference, i am working on BO2 Alpha, which has EVERYTHING labeled, however gentity is in some "random" location and i cant find the actual address itself

**Comment by ujicos** [comment]
No matter what i do, i get this
```he "CL" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Xbox 360 SDK\/bin/win32/Microsoft.Xna.Xbox360.Build.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Xbox 360 SDK\bin\win32\Microsoft.Xna.Xbox360.Build.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.```


I also have some odd error on xam. ```1>Utils.cpp(168): error C2653: 'Xam' : is not a class or namespace name```
```bool isHookSourceAddressValid = Xam::IsAddressValid(m_pHookSource);```

I am following the tutorial you linked. Build fails on both VS22 and VS10. (Preferably id use VS22 if i can).

**Comment by ClementDreptin** [comment]
> Thank you for such a quick reply. I can see a lot of what i need is in there. How would i go about finding stuff like gentity? For reference, i am working on BO2 Alpha, which has EVERYTHING labeled, however gentity is in some "random" location and i cant find the actual address itself

`gentity_s` is usually not labeled in PDBs, or IDA is not able to find it, I don't know. This struct is always a pain in the ass to reverse. Most other structs are labeled by IDA and you can find them in the 'Structure' tab though.

> No matter what i do, i get this `he "CL" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Xbox 360 SDK\/bin/win32/Microsoft.Xna.Xbox360.Build.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Xbox 360 SDK\bin\win32\Microsoft.Xna.Xbox360.Build.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

You can't build using VS2022. Long story short: since VS2022, VS uses the 64 bit version of MSBuild by default and it can't load `Microsoft.Xna.Xbox360.Build.dll` because it was built in 32 bit. I tried everything to make it work but I could never figure it out. I still use VS2022 to manage files and edit the code, but I just build from the command line. MSBuild still ships with a 32 bit version so I just created an alias for myself in my PowerShell profile like so:
```PowerShell
New-Alias msbuild360 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe'
```
I just open the VS2022 integrated terminal (`View > Terminal`) and type `msbuild360`, MSBuild picks the solution file from the current directory by default.
If you get the same error in VS2010, I don't know what to tell other than make sure you carefully followed [those steps](https://github.com/ClementDreptin/ModdingResources/blob/master/Prerequisites/install-env.md).

> I also have some odd error on xam. `1>Utils.cpp(168): error C2653: 'Xam' : is not a class or namespace name bool isHookSourceAddressValid = Xam::IsAddressValid(m_pHookSource);`

That's a copy-paste mistake, you should replace
```C++
bool isHookSourceAddressValid = Xam::IsAddressValid(m_pHookSource);
```
with
```C++
bool isHookSourceAddressValid = MmIsAddressValid(m_pHookSource);
```
I'll push a fix when I find some time.

**Comment by ujicos** [comment]
Thank you. I will keep trying this tomorrow

**Comment by ujicos** [comment]
So i have completely reverted to scratch. I tried to both manually create a solution file as ``Xbox 360 Project>Next>Xbox 360 Game`` and ``Xbox 360 Static Library`` independently. I assume the static library would be the right choice. Either way, i followed your steps in the getting started project, to simply print a hello world. This didn't want to compile.

So i did the most foolproof thing i could think of. I copied the project you provided (GettingStarted), and attempted to build it. There's something really wrong with the path of my SDK it seems. Any idea what the issue may be??

I'll attach the log.
[logged.txt](https://github.com/ClementDreptin/Hayzen/files/11213263/logged.txt)

> c1xx : fatal error C1083: Cannot open source file: 'C:\Program': No such file or directory [I:\1 DOCUMNETS\GitHub\EMLLLY\TesTXEX\TesTXEX.vcxproj]
  c1xx : fatal error C1083: Cannot open source file: 'Files': No such file or directory [I:\1 DOCUMNETS\GitHub\EMLLLY\TesTXEX\TesTXEX.vcxproj]
  c1xx : fatal error C1083: Cannot open source file: '(x86)\Microsoft': No such file or directory [I:\1 DOCUMNETS\GitHub\EMLLLY\TesTXEX\TesTXEX.vcxproj]
  c1xx : fatal error C1083: Cannot open source file: 'Xbox': No such file or directory [I:\1 DOCUMNETS\GitHub\EMLLLY\TesTXEX\TesTXEX.vcxproj]
  c1xx : fatal error C1083: Cannot open source file: '360': No such file or directory [I:\1 DOCUMNETS\GitHub\EMLLLY\TesTXEX\TesTXEX.vcxproj]
  c1xx : fatal error C1083: Cannot open source file: 'SDK\bin\win32\Microsoft.Xna.Xbox360.Build.dll': No such file or directory [I:\1 DOCUMNETS\GitHub\EMLLLY\TesTXEX\TesTXEX.vcxproj]

**Comment by ClementDreptin** [comment]
> So i have completely reverted to scratch. I tried to both manually create a solution file as `Xbox 360 Project>Next>Xbox 360 Game` and `Xbox 360 Static Library` independently. I assume the static library would be the right choice. Either way, i followed your steps in the getting started project, to simply print a hello world. This didn't want to compile.

Static library is not the right choice in your case, XEX files loaded by DashLaunch are Dynamic Link Libraries (DLL) but the wizard doesn't provide an option to create that, you usually need to create an `Xbox 360 Game` then change the application type to `Dynamic Link Libary`.

> So i did the most foolproof thing i could think of. I copied the project you provided (GettingStarted), and attempted to build it. There's something really wrong with the path of my SDK it seems. Any idea what the issue may be??

It does look like there's a path problem somewhere, and it looks like it's caused by spaces. In the path `C:\Program Files (x86)\Microsoft Xbox 360 SDK\bin\win32\Microsoft.Xna.Xbox360.Build.dll`. It tries to load `C:\Program`, then `Files`, then `(x86)\Microsoft`, etc. so spaces are clearly the problem. If you can't build a starter project right after creating it, there's clearly a problem with your installation.

I recommend just wiping the SDK and VS2010 then installing them again. You can uninstall the SDK by running `\path\to\SDK\system\uninstall\xbuninst2.exe`, for VS2010 I don't know. After running the uninstallers, you should also check your `C:\Program Files (x86)`, `%LocalAppData%` and `%AppData%` directories to make sure there's nothing about the SDK or VS2010 anymore (Windows things...).
When you reinstall the SDK, I recommend keeping it in the default location (`C:\Program Files (x86)\Microsoft Xbox 360 SDK`), just in case. **And make sure to do it AFTER installing VS2010**.

**Comment by ujicos** [comment]
Great news, everything works. Thank you alot!

I only have a few questions, one minor, and some possibly a bit harder to answer.

~~1: How do i stop it from auto-launching the xex on build? My settings are below.~~
1: Is it possible for me to change the Start button near "Release_LTCG" and "Xbox 360" so it doesn't auto-launch ?
2: How would i go about finding g_entity (or other structs) via games that have PDBs?
2.5: Is it possible to grab the struct straight from IDA, or would i have to use something along the lines of reclass (if that exists for Xbox even?)

**Comment by ClementDreptin** [comment]
1. The "Start" button is the debug button, which is not really possible to do unless you have a devkit. If you want to build (so just compile, not run), right click on the solution in the solution explorer and click "Build Solution", or just hit Ctrl+Shift+B. If enabled in your project settings, the output binary will be deployed to the console automatically (the deployment process is explained in the other repo).
2. You can't find absolutely all structs in IDA but most of them are found in the PDB and listed in the "Structures" tab. If it's not already open, you can open it by pressing Shift+F9. As a side note, I've only ever found `gentity_s` in CoD4 PDBs, so I don't think you'll be able to find it in a BO2 PDB.
2.5. IDA can identify structures from PDBs and show them like this:
```
00000000 clientState_s   struc # (sizeof=0x94, align=0x4, copyof_4649)
00000000                                         # XREF: clientSession_t/r
00000000 clientIndex:    .long ?
00000004 team:           .long ?                 # enum team_t
00000008 modelindex:     .long ?
0000000C dualWielding:   .long ?
00000010 riotShieldNext: .long ?
00000014 attachModelIndex:.long 6 dup(?)
0000002C attachTagIndex: .long 6 dup(?)
00000044 name:           .byte 32 dup(?)
00000064 maxSprintTimeMultiplier:.float ?
00000068 rank:           .long ?
0000006C prestige:       .long ?
00000070 perks:          .long 2 dup(?)
00000078 diveState:      .long ?
0000007C voiceConnectivityBits:.long ?
00000080 clanAbbrev:     .byte 8 dup(?)
00000088 playerCardIcon: .long ?
0000008C playerCardTitle:.long ?
00000090 playerCardNameplate:.long ?
00000094 clientState_s   ends
```
I have only ever used IDA to reverse stuff, so I don't know if ReClass does anything more than that nor if an equivalent that supports XEX files exists (I highly doubt honestly).

**Comment by ujicos** [comment]
I more so meant finding the address itself for stuff like gentity

**Comment by ClementDreptin** [comment]
If you mean the start of the massive `g_entities` array, you'll have to find a function that references it like `G_InitGame` (there are probably other ones but that's usually the one I use) and then jump to the start of the array from there.

**Comment by ujicos** [comment]
Thanks, this should be helpful. However, for whatever reason, i am unable to build again. Its like the SDK just breaks? I managed to build a xex that did your little SV_ExecuteClientCommand hook that worked fine on BO2 Alpha, now i started a bigger project on the same sln and it doesnt build. Similar error to before...

Only thing i see out of the ordinary is the sudden ``"\/"``
[buildlog.txt](https://github.com/ClementDreptin/Hayzen/files/11216288/buildlog.txt)

**Comment by ClementDreptin** [comment]
Yes, it does look like a path concatenation went wrong. It's also weird that Visual Studio is using forward slashes instead of backslashes. Are you building using VS2010 or MSBuild from the command line?

**Comment by ujicos** [comment]
Current VS2010 as it seems to be the most easy and forward way despite my eyes bleeding from the pale white interface.

Here's VS2022 MSBuild output:
[buildlog.txt](https://github.com/ClementDreptin/Hayzen/files/11216373/buildlog.txt)

**Comment by ujicos** [comment]
Even after dirty-modifying the ``Microsoft.Cpp.Xbox 360.Targets`` to have CL, Link, etc point to the dll it gives the same error (though the slashes are fine now)

EDIT: I copied the dll and renamed it to simply "build.dll", now it seems to build. ~~Can't confirm yet as my project has some syntax errors, but thats odd.~~ Builds fine. Weird.

**Comment by ClementDreptin** [comment]
> I copied the dll and renamed it to simply "build.dll", now it seems to build

It is weird and doesn't look like a long term solution but if it works it works. I would not mess with those files too much though as other SDK related things might rely on them.
