### ISSUE TITLE
Question about “Allow Debug Builds”

### ISSUE THREAD

**Issue by AlfredBall** [ClementDreptin/Hayzen#2]
Just wanted to ask on how the Allow Debug Builds option works, when I load a debug build it does not work, and when I select it after reboot it deactivates.

**Comment by ClementDreptin** [comment]
The workflow is to click on the "Allow Debug Builds" option, if everything succeeds, you should see a notification saying "Reboot to apply changes". You should also have a `Hayzen.ini` file located next to `Hayzen.xex` with a line containing `allowdebugbuilds=true`. If that's the case, the plugin will know it needs to patch the Hypervisor when it loads, allowing you to play [the debug builds listed in README.md](https://github.com/ClementDreptin/Hayzen?tab=readme-ov-file#running-debug-builds).

Hope it helps
