### ISSUE TITLE
Question on adding infinite scrolling? 

### ISSUE THREAD

**Issue by offhostcfw** [ClementDreptin/Hayzen#3]
"I am in the process of learning C++, so I appreciate your understanding if my explanations are not entirely accurate. I am interested in incorporating infinite scrolling into the menu system to seamlessly accommodate additional options, eliminating the need for creating more 'tabs.' If the implementation of infinite scrolling has been introduced in a subsequent version, it could be due to my utilization of an older build from the source. I hope this clarifies my query. If there are any uncertainties, please feel free to reach me on Discord at offhost_cfw. Thank you for your contributions to this project!"

**Comment by ClementDreptin** [comment]
I think there's a misunderstanding on the term "infinite scrolling" here. Infinite scrolling is required when you want to display a list of items but don't know the amount of items ahead of time, or can't afford to fetch all the items at once because they come from an external source (like a Web API). And I doubt it's the case here.
If you have a list of 10 options but can only afford to display 5 at a time, you could create a cursor system and display options based on it.
At first you display options from 1 to 5, then when you try to access the 6th option, you display options from 2 to 6, and so on.

**Comment by offhostcfw** [comment]
Hi sorry for the late response but how would I do that? Can you explain how I would do it? And I'm assuming it would be in the option.cpp/.h file to edit it? Thank you and sorry for the late reply.

**Comment by ClementDreptin** [comment]
It'd be in OptionGroup.h/.cpp, you would have to set a max amount of options to display and scroll between them.

**Comment by offhostcfw** [comment]
Ok I got it where im able to add more options but it is stretching the ui. I try messing with the rendering but I had no luck but freezing when I scroll up or down in seconds. I wish I could send the vid clip in here but it too big.

**Comment by ClementDreptin** [comment]
I've been busy with other things recently but I'll try to implement a max amount of options in an `OptionGroup` if I find the time. I'll update this issue if I make any progress.

**Comment by offhostcfw** [comment]
No problem thank you

**Comment by ClementDreptin** [comment]
The latest version ([v7.3.0](https://github.com/ClementDreptin/Hayzen/releases/tag/v7.3.0)) has scrolling implemented. You can check what had to be done for it to work by looking at [this commit](https://github.com/ClementDreptin/Hayzen/commit/40b0d7e9ecc1e077ceb78bd22f4b09856db6d028). The max amount of options to display before scrolling is hard-coded and is set to 8 for now. If you want to change it, you can change the value of `MAX_OPTIONS_TO_DISPLAY` at [`src/Options/OptionGroup.cpp#L6`](https://github.com/ClementDreptin/Hayzen/blob/master/src/Options/OptionGroup.cpp#L6).

Feel free to close this issue if your initial question is answered.

**Comment by offhostcfw** [comment]
Thank you!!!!
