### ISSUE TITLE
Error	MSB4062	The "CL" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Xbox 360 SDK\/bin/win32/Microsoft.Xna.Xbox360.Build.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Xbox 360 SDK\bin\win32\Microsoft.Xna.Xbox360.Build.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by joker1551** [ClementDreptin/Hayzen#4]
trying to build your current project, and later versions, but i keep getting this error across vs 2022 Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "CL" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Xbox 360 SDK\/bin/win32/Microsoft.Xna.Xbox360.Build.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Xbox 360 SDK\bin\win32\Microsoft.Xna.Xbox360.Build.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	Hayzen	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Xbox 360\Microsoft.Cpp.Xbox 360.Targets	99	
if anyone can help i'd appriate it

**Comment by ClementDreptin** [comment]
Hi,
The README was missing instructions on how to build the project in VS2022, thanks for making me notice!
The instructions are [there](https://github.com/ClementDreptin/Hayzen#development).

**Comment by ItsJokerZz** [comment]
I've since tried and done as mentioned in the README and cannot get it to build on VS2022 on Windows 11, with the same error.
