### ISSUE TITLE
doesnt support rgh3 and xdk consoles

### ISSUE THREAD

**Issue by XeFunky** [ClementDreptin/Hayzen#5]
rgh3 - when launching xex it gives disc read error then takes straight back to dashboard

xdk - when loading the plugin it freezes at the xbox logo screen or when injecting the plugin freezes on dashboard

**Comment by ClementDreptin** [comment]
I have neither of those so I won't be able to reproduce the bugs. You could try to load the plugin with Xbox Watson open and see if you get error messages.

**Comment by XeFunky** [comment]
do you have a discord server for hayzen or is it just posting here?

**Comment by ClementDreptin** [comment]
No I don't have a discord server, github issues have done the job so far

**Comment by XeFunky** [comment]
there is no indication in the kdnet log that says why it freezes at the xbox 360 screen or when loading the plugin via a module loader

**Comment by ClementDreptin** [comment]
If you have a stealth server you can try to remove it and clear your system cache. I had a freezing issue with a stealth server one day and that's what solved the problem.

**Comment by XeFunky** [comment]
even without a server it still freezes on the xdk console with no indication why its doing it. v1 loads for a split second then it freezes again no explanation

**Comment by ClementDreptin** [comment]
If you have Xbox Watson open on your computer while the crash happens, you might see the memory address where the crash happens, that could help a little bit.

**Comment by XeFunky** [comment]
if you have discord add me as it will be easier than here

discord: thatxdkguy

**Comment by ClementDreptin** [comment]
Fixed in [v8.0.1](https://github.com/ClementDreptin/Hayzen/releases/tag/v8.0.1).
